### ISSUE TITLE
PHP fatal error. Call to undefined function.

### ISSUE THREAD

**Issue by hansullrich** [stephenscaff/The-JumpOff-Wp-Kit#1]
Hey first of all, big fan of what you and UI are doing. 

I cloned this theme into the themes folder but got the white screen of death. So I checked debug.log and got this: 

[04-Feb-2016 02:06:34 UTC] PHP Fatal error:  Call to undefined function get_field() in /Users/***/test/wp-content/themes/thejumpoff/partials/partial-head.php on line 34

I removed all the links with the <?php the_field('seo_keywords');?> and <?php the_field('seo_description');?>

I don't have the time to search for the_field right now, and maybe it's proprietary and you left it out on purpose. But just wanted to let you know, because without that undefined function, everything works great right out of the box.

This is a great repo for front-end devs who use codekit. Thanks for making it open source.

**Comment by stephenscaff** [comment]
I'm in the process (albeit half ass) of updating all that into a better structure. Will push sometime soon.
But, those errors are related to Advanced Custom Fields. Add the plugin, it's nice for creating custom fields. Of course, we could wrap all calls into a if function exists.....

**Comment by stephenscaff** [comment]
Okay. Cleaned everything up. Restructured the front end side of things to match our current starter at Urban. Restructured wp as well, and wrapped the acf calls (for seo stuff in head) in the native wp's native get meta call to prevent errors before you activate ACF. Cut the fat. Provided some minimal styles and basic markup to getcha going. Included example files to rename.

**Comment by hansullrich** [comment]
Dope. Working seamlessly.
